Fix umockdev-vala testcase
martinpitt/umockdev pull request #261
Opened 2024-12-28 19:38 UTC by hdeller

The umockdev-vala testcase randomly fails on some platforms (hppa, sparc64, powerpc, see:[1][2][3]) because the ioctl() testcase checks the return value pointed to by "ret" in ioctl_tree_execute() which might have stale data as it wasn't initialized.

Fix it by properly initializing the return code.
Additionally force all code paths to provide a valid return code address.

Tested on hppa-linux and armhf-linux.

[1] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=hppa&ver=0.19.0-1&stamp=1735373270&raw=0
[2] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=powerpc&ver=0.19.0-1&stamp=1735375553&raw=0
[3] https://buildd.debian.org/status/fetch.php?pkg=umockdev&arch=sparc64&ver=0.19.0-1&stamp=1735380455&raw=0

2024-12-29 15:44 UTC, martinpitt requested changes
Thanks for spotting this! Do you want to fix it up yourself, or want me to take over?

2024-12-29 15:44 UTC, martinpitt commented on src/ioctl_tree.c
> +    *ret = 0;
This "succeed by default" semantics is bad, as it hides errors. src/umockdev-ioctl.vala initializes the `ret` value to -1, so this is also inconsistent with the current behaviour.

Let's initialize to -1 here,  and drop the `else` in line 376 instead.

Let's also add an assertion that `ret` is not NULL, to document that requirement and make errors clearer.

2024-12-29 15:44 UTC, martinpitt commented on tests/test-umockdev-vala.vala
> +  assert_cmpint (Posix.ioctl (fd, Ioctl.USBDEVFS_CONNECTINFO, ref ci), CompareOperator.EQ, 0);
The -1 check was quite deliberate, see above.

2024-12-29 15:44 UTC, martinpitt commented on tests/test-umockdev-vala.vala
> -  errno = 0;
This should go back. This test runs the actual ioctl, and checking the error code gives some additional confidence that this happens. It is of course more robust to also reset errno to 0 before, just like in the next check.

2024-12-29 15:44 UTC, martinpitt commented on tests/test-umockdev-vala.vala
> -  assert_cmpint (Posix.errno, CompareOperator.EQ, Posix.ENOTTY);
dito

2024-12-29 15:45 UTC, martinpitt commented on src/ioctl_tree.c
> +    *ret = 0;
... and also drop the then-redundant initialization in umockdev-ioctl.vala

2024-12-30 11:05 UTC, martinpitt commented
Thanks @hdeller ! I fixed the points above, and also cleaned up the commit message a bit.

2024-12-30 11:51 UTC, martinpitt commented
Thanks @hdeller ! I fixed the points above, and also cleaned up the commit message a bit. Before I do a new release, let's discuss/sort out #262

2024-12-30 11:51 UTC, merged

2024-12-30 13:51 UTC, hdeller commented
problem still happens on hppa build:
# DEBUG: umockdev.vala:1414: parsing device description for /devices/mycam
# DEBUG: umockdev.vala:1492: creating device /devices/mycam (subsystem usb)
# DEBUG: umockdev.vala:1538: create_node_for_device: creating file device /tmp/umockdev.SLZ0Z2/dev/001
# DEBUG: umockdev.vala:832: umockdev_testbed_uevent: sending uevent add for device /sys/devices/mycam
**
ERROR:../tests/test-umockdev-vala.vala:284:t_usbfs_ioctl_static: assertion failed (ioctl (fd2, TIOCSBRK, 0) == 0): (-1 == 0)
not ok /umockdev-testbed-vala/usbfs_ioctl_static - ERROR:../tests/test-umockdev-vala.vala:284:t_usbfs_ioctl_static: assertion failed (ioctl (fd2, TIOCSBRK, 0) == 0): (-1 == 0)

2024-12-30 13:58 UTC, hdeller commented
With this patch testcase succeeds on hppa and s390x:

diff --git a/tests/test-umockdev-vala.vala b/tests/test-umockdev-vala.vala
index 0d4add0..9cd88e2 100644
--- a/tests/test-umockdev-vala.vala
+++ b/tests/test-umockdev-vala.vala
@@ -281,8 +281,8 @@ E: SUBSYSTEM=usb
   // unknown ioctls do work on non-emulated devices
   int fd2 = Posix.open ("/dev/tty", Posix.O_RDWR, 0);
   if (fd2 > 0) {
-      assert_cmpint (Posix.ioctl (fd2, Ioctl.TIOCSBRK, 0), CompareOperator.EQ, 0);
-      assert_cmpint (Posix.errno, CompareOperator.EQ, 0);
+      assert_cmpint (Posix.ioctl (fd2, Ioctl.TIOCSBRK, 0), CompareOperator.EQ, -1);
+      assert_cmpint (Posix.errno, CompareOperator.EQ, Posix.ENOTTY);
       Posix.close (fd2);
   }